# Project configuration
project_name: myproject
project_user: "{{ project_name }}"
project_group: "{{ project_name }}"
project_home: "/opt/{{ project_name }}"
deploy_user: "{{ project_name }}_deploy"

# Docker configuration
docker_packages:
  - docker.io
  - docker-compose-plugin

# Developer SSH keys (add your team's keys here)
developers:
  - name: touchme
    root_access: true
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnUneA6+mOT+vfGHJfLOT/snDk/nemNV/cOh8WhZrKomIEVWcd8UmgqE/d8xBK1K3axiRN1v01EWXun2yNC4hxsaxJ1m1OQb6OGjHGy4Y4ta24YTnE13aSQ/Qrpd9fLA5M//xgoCiF5YDtcu9JODqkF8bl6IprgRaGi6nrQNHJBakmfP/o8ReK6v5YDzixsWkYkE8uo6oeGLc47ZQoC0JDMSjKOZocYxXVjuuvZeDcl6R4Ys2ijJABZTsrkcOvqmYN8zGIQQz2tiMWgYtDhUCjcn5A4OmefoAMiGYIsO2cpQIueMQjPIYdSnusQgp/PPFsVYwlMFL8xaXaI5IC0Oql90dWwZCd6Kxc49iZUvBVJTjtb/ZSF5mAnMlIb1u0619oHHZl5qVi+pHNVjo9/r5Wyz6NWaA8IbOdVIavmtpL/62Kvbi2qnzWUUfEQZBNrWwMyY/+ahG76IvN6VTQPv4LK4pl4KxOlQHAqYHiFK8Vo+3j6nIS9IeQcGJgxI6IFTvT2FUMFNVifVBXKm1W5MRcZ8bXnSm5DJETEBfrbVUfBUfQMjtUFxcqFhQXD0S+d1vRe8ETVYr0e4x71jzxtadQWmEHX+56bqC7GYnHWGYwxLy45YvgeVoqJKTwgn8n3MyMOhaQy/kTGR/3xSSavws9/m9FqAfPp/Ry9+tsFv8i8w== @touchmeangel"

# GitHub Actions deploy key
github_actions_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIZaRwfStSoJ/pDPSsmsaeI51xZdPM6HcVIyScQwn7DVs1UmLWP70Lv5xzaqXxKq7SEOT+ugzgivGoHbrMCM2RumnqRGvCcDmrtv/81dir8FfHlCJ3uziylMCDLguPyGFoVXgKok9QyYK9dpV2CXFx7RSnB/38/8iWT4G5DhQA/P2rh05YpZG3kQM1Yl0Wyp7E/H2TTODkvxl7MRiMW2U8AYm/zS1v/Mlgtyy6gsgT+pCGVp1VMh3rzgonE9m+29alZIWvfAcjiYngaX+sk7o9ihbJ3cHIJu3ax7NO5vAhx6pVFLZJiw22IiGZq5/xnuZS/mMx4OpLVXKpMyZytr3MX5fPTz3Uns3tSzNXirJvcZ2r70gLVPAMcHNdql/s/2iq1NutgeJX5XSY9BBvLnAEmfQz/v4BsYUKcwc+CjhWLOpgctRueeb2KgNWlQfCnZPJn143HLXj2Gi8SQvA550LHgqNuq/ql9STfwZ8T/iNCi5XX8IdbZDBvaV8L3RDZ2fsj6q4+puFs6KHIr0u5QZH6PQDhUy0G+Dv0wi5saCJ1fH9B+dFZppoajqIniypF6dZb+eAQm5ykjGYdiqmXbcIGeYT0+xX7enEcftakeIaWZzmLKVlwNnFWTILWNQXDvlO8OCJrzZ7yNTP5uok3FXJFkRrkHMReoqt0TWmvqXODQ== github@207.154.218.253"

# Firewall ports
firewall_allowed_ports:
  - "22"
  - "443"